version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Expose port 5173 on the host to port 5173 in the container


  backend:
    build:
      context: ./backend  # Path to your backend directory
      dockerfile: Dockerfile  # Dockerfile in the backend directory
    ports:
      - "8000:8000"  # Expose backend on localhost:8000
    depends_on:
      - db  # Ensure backend waits for MongoDB
    volumes:
      - ./backend:/app  # Mount backend code for development


  db:
    image: mongo:5.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"  # Expose MongoDB on localhost
    volumes:
      - mongo_data:/data/db  # Persistent volume for MongoDB data

volumes:
  mongo_data: