# Docker Compose for LOCAL DEVELOPMENT ONLY
# For production, use Modal: modal deploy backend/modal_app.py

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        PORT: ${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - PORT=${FRONTEND_PORT}
      - VITE_API_URL=http://localhost:${BACKEND_PORT}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        PORT: ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.local
    environment:
      - PORT=${BACKEND_PORT}
