# Production setup: Frontend only
# Backend runs on Modal: https://modal.com
#
# For local development with both services, use:
#   docker compose -f compose.dev.yaml up

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        PORT: ${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - PORT=${FRONTEND_PORT}
      # Point to Modal backend in production
      - VITE_API_URL=${BACKEND_URL}